import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { card, input, btn, heading, muted, pre } from "./styles";

interface GenerateResult {
  model: string;
  content: string;
}

export default function GeneratePanel() {
  const [prompt, setPrompt] = useState("");
  const [about, setAbout] = useState("");
  const [niche, setNiche] = useState("");
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<GenerateResult[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [active, setActive] = useState(0);

  async function run() {
    if (!prompt.trim()) return;
    setLoading(true);
    setError(null);
    setResults([]);
    try {
      const r = await invoke<GenerateResult[]>("run_generate", {
        prompt: prompt.trim(),
        about: about.trim() || null,
        niche: niche.trim() || null,
        models: null,
      });
      setResults(r);
      setActive(0);
    } catch (e) {
      setError(String(e));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <h1 style={heading}>Generate</h1>
      <p style={muted}>Produce GEO-optimized markdown for any target query.</p>

      <div style={card}>
        <input style={{ ...input, marginBottom: 10 }}
          placeholder="Target query (e.g. 'best deterministic runtime for edge AI')"
          value={prompt} onChange={e => setPrompt(e.target.value)}
          onKeyDown={e => e.key === "Enter" && run()} />
        <div style={{ display: "flex", gap: 10, marginBottom: 12 }}>
          <input style={{ ...input, flex: 2 }}
            placeholder="About your project (e.g. 'myproject.io is a fast Rust CLI')"
            value={about} onChange={e => setAbout(e.target.value)} />
          <input style={{ ...input, flex: 1 }}
            placeholder="Niche (optional)"
            value={niche} onChange={e => setNiche(e.target.value)} />
        </div>
        <button style={btn} onClick={run} disabled={loading || !prompt.trim()}>
          {loading ? "Generating…" : "Generate Content"}
        </button>
        {error && <div style={{ color: "#f85149", fontSize: 13, marginTop: 8 }}>Error: {error}</div>}
      </div>

      {results.length > 0 && (
        <div style={card}>
          {results.length > 1 && (
            <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
              {results.map((r, i) => (
                <button key={i} onClick={() => setActive(i)}
                  style={{
                    background: i === active ? "#238636" : "#21262d",
                    color: "#fff",
                    border: "1px solid #30363d",
                    borderRadius: 6,
                    padding: "4px 12px",
                    fontSize: 12,
                    cursor: "pointer",
                    fontFamily: "inherit",
                  }}>
                  {r.model}
                </button>
              ))}
            </div>
          )}
          <pre style={pre}>{results[active]?.content}</pre>
          <div style={{ marginTop: 12, fontSize: 12, color: "#8b949e" }}>
            Generated by {results[active]?.model} ·{" "}
            <span style={{ cursor: "pointer", color: "#58a6ff" }}
              onClick={() => navigator.clipboard.writeText(results[active]?.content ?? "")}>
              Copy to clipboard
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
